function protocol = frozen_robustness_protocol()
%FROZEN_ROBUSTNESS_PROTOCOL Final finite-horizon evaluation definition.
%   This protocol was selected prospectively from the 8/10/12 s horizon
%   and one-factor threshold sensitivity study completed on 4 August 2026.
%   A focused 12/14/16 s extension confirmed that the Controller D
%   sagittal boundary classifications were already stable at 12 s.
%
%   "Recovered" means upright and sustainably inside the declared final
%   recovery envelope. It is a finite-horizon outcome, not a claim of
%   asymptotic stability.

protocol = struct( ...
    "version", 1, ...
    "frozenDate", "2026-08-04", ...
    "scientificRole", ...
        "Final identical-condition finite-horizon robustness evaluation", ...
    "lateralForceLevels_N", [25 50 75 100], ...
    "sagittalForceLevels_N", [50 75 100], ...
    "pulseStart_s", 2, ...
    "pulseDuration_s", 0.1, ...
    "stopTime_s", 12, ...
    "finalDwell_s", 2, ...
    "recoveryTimeDwell_s", 0.5, ...
    "fallVerticalDrop_m", 0.5, ...
    "fallHorizontalTravel_m", 1, ...
    "fallRotation_deg", 30, ...
    "contactLoadThreshold_N", 1, ...
    "actuatorTorqueLimit_Nm", 100, ...
    "saturationTolerance_Nm", 1e-6, ...
    "recoveryDisplacementRMS_m", 0.025, ...
    "recoveryTiltRMS_deg", 2, ...
    "recoveryVelocityRMS_m_s", 0.02, ...
    "settlingRatioLimit", 0.75, ...
    "smallDisplacementRMS_m", 0.005, ...
    "smallTiltRMS_deg", 0.5, ...
    "horizonSensitivityResult", fullfile("Results", ...
        "BenchmarkProtocolSensitivity", "20260804_104320"), ...
    "focusedExtensionResult", fullfile("Results", ...
        "ControllerDSagittalHorizonExtension", "20260804_121055"));
end
