function simulationInput = reset_residual_rl_environment( ...
    simulationInput, protocol)
%RESET_RESIDUAL_RL_ENVIRONMENT Apply frozen A and one sampled disturbance.

arguments
    simulationInput
    protocol struct = residual_rl_training_protocol("validation")
end

model = "HumanoidModel_ResidualRL";
frozen = frozen_pd_gravity_controllers();
controller = frozen.A;
trainingCase = sample_residual_rl_training_case(protocol);

simulationInput = simulationInput.setVariable("alpha", controller.alpha);
simulationInput = simulationInput.setVariable( ...
    "u_hip_frontal", controller.nominalCommands.hip);
simulationInput = simulationInput.setVariable( ...
    "u_knee", controller.nominalCommands.knee);
simulationInput = simulationInput.setVariable( ...
    "u_ankle_pitch", controller.nominalCommands.ankle);
simulationInput = simulationInput.setVariable( ...
    "u_hip_sagittal", controller.nominalCommands.hipSagittal);
for index = 1:numel(frozen.shared.outerPGainNames)
    simulationInput = simulationInput.setVariable( ...
        frozen.shared.outerPGainNames(index), ...
        frozen.shared.outerPGainValues(index));
end
for index = 1:numel(frozen.shared.outerDGainNames)
    simulationInput = simulationInput.setVariable( ...
        frozen.shared.outerDGainNames(index), ...
        frozen.shared.outerDGainValues(index));
end
simulationInput = simulationInput.setVariable( ...
    "Rx_ref", frozen.shared.torsoRollReference_rad);
simulationInput = simulationInput.setVariable( ...
    "y_ref", frozen.shared.torsoForwardReference_m);
simulationInput = simulationInput.setVariable( ...
    "x_ref", frozen.shared.torsoLateralReference_m);
simulationInput = simulationInput.setVariable("residualRLEnabled", 1);
simulationInput = simulationInput.setVariable("residualRLUseAgent", 1);
if isfield(protocol,"residualTorqueLimit_Nm")
    simulationInput = simulationInput.setVariable( ...
        "residualRLTorqueLimit_Nm",protocol.residualTorqueLimit_Nm);
end
simulationInput = simulationInput.setVariable( ...
    "robustnessForceVector_N", trainingCase.forceVector_N);
simulationInput = simulationInput.setVariable( ...
    "robustnessForceStart_s", trainingCase.onset_s);
simulationInput = simulationInput.setVariable( ...
    "robustnessForceDuration_s", trainingCase.duration_s);
simulationInput = simulationInput.setModelParameter( ...
    "StopTime", string(trainingCase.stopTime_s));
simulationInput = simulationInput.setBlockParameter( ...
    model + "/Gain", "Gain", "1");
simulationInput = simulationInput.setBlockParameter( ...
    model + "/Gain2", "Gain", "alpha");
end
