function results = train_residual_rl_authority_ablation( ...
        torqueLimits_Nm, maxEpisodes, randomSeed, outputRoot, showPlots)
%TRAIN_RESIDUAL_RL_AUTHORITY_ABLATION Train matched physical-action bounds.
%   Trains independent SAC agents while changing only the mapping from the
%   normalized two-action output [-1,1] to physical hip-sagittal residual
%   torque. The nominal controller, observations, reward, disturbance
%   distribution, random seed, agent settings and episode budget remain
%   identical. The established seed-0 +/-15 Nm agent is not retrained by
%   default; it is the reference condition for the final evaluation.

arguments
    torqueLimits_Nm (1,:) double ...
        {mustBeFinite,mustBePositive} = [5 10]
    maxEpisodes (1,1) double {mustBeInteger,mustBePositive} = 100
    randomSeed (1,1) double {mustBeInteger,mustBeNonnegative} = 0
    outputRoot (1,1) string = fullfile( ...
        project_codes_root(),"Results", ...
        "ResidualRLAuthorityAblationTraining")
    showPlots (1,1) logical = true
end

assert(numel(unique(torqueLimits_Nm))==numel(torqueLimits_Nm), ...
    "AuthorityAblation:DuplicateLimit", ...
    "Every requested residual-torque limit must be unique.");

stamp=string(datetime("now","Format","yyyyMMdd_HHmmss"));
resultDirectory=fullfile(outputRoot,stamp);
mkdir(resultDirectory);
trainingRuns=cell(numel(torqueLimits_Nm),1);
manifest=table(torqueLimits_Nm(:),repmat(maxEpisodes,numel(torqueLimits_Nm),1), ...
    repmat(randomSeed,numel(torqueLimits_Nm),1),strings(numel(torqueLimits_Nm),1), ...
    'VariableNames',{'ResidualTorqueLimit_Nm','MaxEpisodes', ...
    'RandomSeed','ResultDirectory'});

fprintf("\nResidual-RL physical-authority ablation training\n");
fprintf("Limits: +/- %s Nm; episodes: %d; seed: %d\n", ...
    mat2str(torqueLimits_Nm),maxEpisodes,randomSeed);
fprintf("All non-authority settings are held fixed.\n");
fprintf("Output: %s\n\n",resultDirectory);

for index=1:numel(torqueLimits_Nm)
    limit=torqueLimits_Nm(index);
    fprintf("[%d/%d] Training independent +/-%.6g Nm agent\n", ...
        index,numel(torqueLimits_Nm),limit);
    runRoot=fullfile(resultDirectory,sprintf("limit_%gNm",limit));
    run=train_residual_rl_sac(maxEpisodes,randomSeed,runRoot, ...
        showPlots,limit);
    trainingRuns{index}=run;
    manifest.ResultDirectory(index)=run.resultDirectory;
    writetable(manifest,fullfile(resultDirectory,"training_manifest.csv"));
    save(fullfile(resultDirectory,"training_checkpoint.mat"), ...
        "trainingRuns","manifest","torqueLimits_Nm", ...
        "maxEpisodes","randomSeed","-v7.3");
end

save(fullfile(resultDirectory,"training_results.mat"), ...
    "trainingRuns","manifest","torqueLimits_Nm", ...
    "maxEpisodes","randomSeed","-v7.3");
results=struct("resultDirectory",string(resultDirectory), ...
    "manifest",manifest,"trainingRuns",{trainingRuns}, ...
    "referenceTorqueLimit_Nm",15, ...
    "referenceDescription", ...
        "Existing frozen seed-0 RL75 policy at +/-15 Nm");
fprintf("Authority-ablation training written to %s\n",resultDirectory);
end
