function frozen = frozen_pd_gravity_controllers()
%FROZEN_PD_GRAVITY_CONTROLLERS Frozen A and D controller definitions.
%   FROZEN = FROZEN_PD_GRAVITY_CONTROLLERS() returns the controller
%   configurations selected on 26 July 2026 after:
%     - gravity sign/order/unit and all-joint validation;
%     - correction of the symmetric hip-sagittal nominal-command path;
%     - repetition of the nominal sweep and four-case ablation;
%     - repetition of the matched outer-feedback gain-authority experiment.
%
%   These definitions are the fixed nominal controllers for subsequent
%   disturbance, uncertainty, actuator-nonideality, and residual-RL
%   comparisons. Do not retune either controller within an evaluation
%   scenario. Both controllers retain the original outer feedback gains,
%   inner joint stiffness, and joint damping.

thisDirectory = string(project_codes_root());
fourCaseRelative = fullfile("Results", ...
    "GravityNominalFourCaseAblation", "20260726_212925", ...
    "processed_results.mat");
gainRelative = fullfile("Results", ...
    "MatchedFeedbackGainAuthority", "20260726_214137", ...
    "processed_results.mat");
fourCaseFile = fullfile(thisDirectory, fourCaseRelative);
gainFile = fullfile(thisDirectory, gainRelative);
% Release runtime snapshot contains only the exact selected parameters.
% Historical result paths below are provenance, not runtime dependencies.
parameterFile = fullfile(thisDirectory,"setup","controller_baseline_parameters.mat");
assert(isfile(parameterFile),"FrozenControllers:ParameterSnapshotMissing", ...
    "Required release parameter snapshot not found: %s",parameterFile);
selected = load(parameterFile, "baseNominal", "retunedNominal", ...
    "fullCorrection", "initialGravity", "nominalFraction");
assert(isfield(selected, "nominalFraction") && ...
    abs(selected.nominalFraction - 1.15) < 1e-12, ...
    "FrozenControllers:UnexpectedNominalFraction", ...
    "Selected four-case result does not contain nominal fraction 1.15.");

% Exact values defined by the frozen parameter script at selection time.
pGainNames = ["kp_ankle_qx", "kp_hip_qx", "kp_ankle_y", ...
    "kp_hip_y", "kp_hip_dz", "kp_hip_sag_qy", "kp_hip_sag_x"];
dGainNames = ["kd_ankle_wx", "kd_hip_wx", "kd_ankle_vy", ...
    "kd_hip_vy", "kd_hip_vz", "kd_hip_sag_wy", "kd_hip_sag_vx"];
pGainValues = [-0.7, 1, 6, -4, -4, 10, -10];
dGainValues = [-0.1, 0.1, 1, -1.7, -0.1, 1, -1];
expectedBaseNominal = struct( ...
    "hip", 1/6, "knee", -11/17, "ankle", -1/2, ...
    "hipSagittal", 0);
assertNominalEqual(selected.baseNominal, expectedBaseNominal, ...
    "The selected four-case result does not use the frozen baseline " + ...
    "nominal commands.");

shared = struct( ...
    "outerPGainNames", pGainNames, ...
    "outerPGainValues", pGainValues, ...
    "outerDGainNames", dGainNames, ...
    "outerDGainValues", dGainValues, ...
    "outerKpScale", 1, ...
    "outerKdScale", 1, ...
    "hipFrontalStiffness_NmPerRad", 80, ...
    "hipSagittalStiffness_NmPerRad", 80, ...
    "kneeStiffness_NmPerRad", 80, ...
    "ankleStiffness_NmPerRad", 80, ...
    "hipFrontalDamping_NmsPerRad", 1, ...
    "hipSagittalDamping_NmsPerRad", 1, ...
    "kneeDamping_NmsPerRad", 1, ...
    "ankleDamping_NmsPerRad", 1, ...
    "jointTorqueLimit_Nm", 100, ...
    "finalLegActuatorTorqueLimit_Nm", 100, ...
    "torsoRollReference_rad", deg2rad(-5), ...
    "torsoForwardReference_m", 0.25, ...
    "torsoLateralReference_m", 0, ...
    "zeroTorqueJoints", [ ...
        "right_hip_transverse"
        "right_ankle_roll"
        "left_hip_transverse"
        "left_ankle_roll"]);

controllerA = struct( ...
    "id", "A", ...
    "name", "Frozen corrected PD baseline", ...
    "alpha", 0, ...
    "usesGravityFeedforward", false, ...
    "usesRetunedNominalCommands", false, ...
    "nominalFraction", 0, ...
    "nominalCommands", selected.baseNominal, ...
    "outerKpScale", 1, ...
    "outerKdScale", 1);

controllerD = struct( ...
    "id", "D", ...
    "name", "Frozen equilibrium-compatible PD plus gravity", ...
    "alpha", 1, ...
    "usesGravityFeedforward", true, ...
    "usesRetunedNominalCommands", true, ...
    "nominalFraction", selected.nominalFraction, ...
    "nominalCommands", selected.retunedNominal, ...
    "outerKpScale", 1, ...
    "outerKdScale", 1);

provenance = struct( ...
    "frozenDate", "2026-07-26", ...
    "modelFile", "HumanoidModel_BaselineBalanceControl.slx", ...
    "parameterScript", "humanoid_walker_parameters.m", ...
    "fourCaseProcessedResult", string(fourCaseRelative), ...
    "matchedGainProcessedResult", string(gainRelative), ...
    "modelSha256", ...
        "BED12F6143D3EAEF0C0485018A9A9AAC4123A25BDB5DA2973A80EB044181C037", ...
    "parameterScriptSha256", ...
        "3A2E3B9A1DB93A2EECA6188E123BCEF4FFF39976A2C694A30BF3AB50286BDE95", ...
    "fourCaseResultSha256", ...
        "7B7EF656AC3DFEFDDE02913B7C8CDBCB0E261F6C77C7224AEFA77B361D796A93", ...
    "matchedGainResultSha256", ...
        "63513DF7C538C3DC74F421487341FC17EE950211FDDD2B8C325C4DE1367E5F2E");

frozen = struct( ...
    "version", 2, ...
    "scientificRole", ...
        "Frozen nominal baselines for identical-condition robustness and residual-RL comparisons.", ...
    "comparisonRule", ...
        "Do not retune controller A or D within disturbance, uncertainty, actuator, or RL evaluation scenarios.", ...
    "shared", shared, ...
    "A", controllerA, ...
    "D", controllerD, ...
    "initialGravityTorque_Nm", selected.initialGravity, ...
    "fullNominalCorrection", selected.fullCorrection, ...
    "provenance", provenance);
end

function assertNominalEqual(actual, expected, message)
actualValues = [actual.hip, actual.knee, actual.ankle, ...
    actual.hipSagittal];
expectedValues = [expected.hip, expected.knee, expected.ankle, ...
    expected.hipSagittal];
assert(max(abs(actualValues - expectedValues)) < 1e-12, ...
    "FrozenControllers:BaselineNominalMismatch", message);
end
