function results = analyze_all_motor_drive_nominal_oscillation(nominalResults)
%ANALYZE_ALL_MOTOR_DRIVE_NOMINAL_OSCILLATION Quantify nominal sway.
% Uses saved trajectories from benchmark_all_motor_drive_nominal_controllers.
% No simulation or model edit is performed. Absolute late-window errors are
% separated from mean-centred oscillation amplitudes and velocities.

arguments
    nominalResults (1,1) struct
end
required=["definitions","trajectories","protocol","resultDirectory"];
for name=required
    assert(isfield(nominalResults,name),"MotorOscillation:MissingField", ...
        "Input results do not contain %s.",name);
end
definitions=nominalResults.definitions;
trajectories=nominalResults.trajectories;
p=nominalResults.protocol;
assert(height(definitions)==numel(trajectories), ...
    "MotorOscillation:RunCount","Definition/trajectory count mismatch.");

earlyStart_s=2;
windowDuration_s=p.finalDwell_s;
earlyEnd_s=earlyStart_s+windowDuration_s;
lateStart_s=p.stopTime_s-windowDuration_s;
rows=cell(height(definitions),1);
for index=1:height(definitions)
    rows{index}=metricsForRun(trajectories{index},definitions(index,:), ...
        earlyStart_s,earlyEnd_s,lateStart_s,p.stopTime_s, ...
        p.settlingRatioLimit);
end
metrics=vertcat(rows{:});
resultDirectory=string(nominalResults.resultDirectory);
writetable(metrics,fullfile(resultDirectory,"nominal_oscillation_metrics.csv"));
save(fullfile(resultDirectory,"nominal_oscillation_analysis.mat"), ...
    "metrics","earlyStart_s","earlyEnd_s","lateStart_s", ...
    "windowDuration_s","-v7.3");
results=struct("metrics",metrics,"earlyWindow_s",[earlyStart_s earlyEnd_s], ...
    "lateWindow_s",[lateStart_s p.stopTime_s], ...
    "resultDirectory",resultDirectory);
fprintf("\nNominal oscillation analysis\n");
fprintf("Early comparison window: %.1f-%.1f s\n",earlyStart_s,earlyEnd_s);
fprintf("Late window: %.1f-%.1f s\n",lateStart_s,p.stopTime_s);
disp(metrics);
fprintf("Results added to %s\n",resultDirectory);
end

function row=metricsForRun(x,d,earlyStart,earlyEnd,lateStart,lateEnd,ratioLimit)
t=x.time(:); q=x.q;
assert(size(q,2)==22 && size(q,1)==numel(t), ...
    "MotorOscillation:TrajectoryShape","Expected an N-by-22 trajectory.");
early=t>=earlyStart & t<=earlyEnd;
late=t>=lateStart & t<=lateEnd;
assert(nnz(early)>=2 && nnz(late)>=2,"MotorOscillation:WindowSamples", ...
    "Insufficient trajectory samples in an analysis window.");
q0=q(1,:); delta=q-q0;

earlyValues=windowMetrics(t(early),delta(early,:));
lateValues=windowMetrics(t(late),delta(late,:));
fullValues=windowMetrics(t,delta);
translationRatio=safeRatio(lateValues.CenteredTranslationRMS_m, ...
    earlyValues.CenteredTranslationRMS_m);
rotationRatio=safeRatio(lateValues.CenteredRotationRMS_deg, ...
    earlyValues.CenteredRotationRMS_deg);
jointRatio=safeRatio(lateValues.CenteredJointRMS_deg, ...
    earlyValues.CenteredJointRMS_deg);
linearVelocityRatio=safeRatio(lateValues.TorsoLinearVelocityRMS_m_s, ...
    earlyValues.TorsoLinearVelocityRMS_m_s);
angularVelocityRatio=safeRatio(lateValues.TorsoAngularVelocityRMS_deg_s, ...
    earlyValues.TorsoAngularVelocityRMS_deg_s);
jointVelocityRatio=safeRatio(lateValues.JointVelocityRMS_deg_s, ...
    earlyValues.JointVelocityRMS_deg_s);
worstRatio=max([translationRatio rotationRatio jointRatio ...
    linearVelocityRatio angularVelocityRatio jointVelocityRatio]);
if worstRatio<=ratioLimit
    trend="decaying_by_all_ratios";
elseif worstRatio<=1
    trend="not_clearly_decaying";
else
    trend="one_or_more_metrics_growing";
end

row=table(d.Controller,d.Actuation,d.Enable, ...
    fullValues.TorsoTranslationPathLength_m, ...
    fullValues.TorsoVerticalCumulativeTravel_m, ...
    fullValues.TorsoRotationPathLength_deg, ...
    fullValues.JointConfigurationPathLength_deg, ...
    lateValues.TorsoTranslationPathLength_m, ...
    lateValues.TorsoVerticalCumulativeTravel_m, ...
    lateValues.TorsoRotationPathLength_deg, ...
    lateValues.JointConfigurationPathLength_deg, ...
    lateValues.AbsoluteTranslationRMS_m, ...
    lateValues.AbsoluteRotationRMS_deg, ...
    lateValues.AbsoluteJointRMS_deg, ...
    lateValues.CenteredTranslationRMS_m, ...
    lateValues.TranslationPeakToPeak_m, ...
    lateValues.CenteredRotationRMS_deg, ...
    lateValues.RotationPeakToPeak_deg, ...
    lateValues.CenteredJointRMS_deg, ...
    lateValues.MaximumJointPeakToPeak_deg, ...
    lateValues.TorsoLinearVelocityRMS_m_s, ...
    lateValues.TorsoAngularVelocityRMS_deg_s, ...
    lateValues.JointVelocityRMS_deg_s,translationRatio,rotationRatio, ...
    jointRatio,linearVelocityRatio,angularVelocityRatio, ...
    jointVelocityRatio,worstRatio,trend, ...
    'VariableNames',{'Controller','Actuation','Enable', ...
    'FullTorsoTranslationPathLength_m', ...
    'FullTorsoVerticalCumulativeTravel_m', ...
    'FullTorsoRotationPathLength_deg', ...
    'FullJointConfigurationPathLength_deg', ...
    'LateTorsoTranslationPathLength_m', ...
    'LateTorsoVerticalCumulativeTravel_m', ...
    'LateTorsoRotationPathLength_deg', ...
    'LateJointConfigurationPathLength_deg', ...
    'LateAbsoluteTorsoTranslationRMS_m', ...
    'LateAbsoluteTorsoRotationRMS_deg','LateAbsoluteJointRMS_deg', ...
    'LateCenteredTorsoTranslationRMS_m','LateTorsoTranslationPeakToPeak_m', ...
    'LateCenteredTorsoRotationRMS_deg','LateTorsoRotationPeakToPeak_deg', ...
    'LateCenteredJointRMS_deg','LateMaximumJointPeakToPeak_deg', ...
    'LateTorsoLinearVelocityRMS_m_s','LateTorsoAngularVelocityRMS_deg_s', ...
    'LateJointVelocityRMS_deg_s','TranslationOscillationLateEarlyRatio', ...
    'RotationOscillationLateEarlyRatio','JointOscillationLateEarlyRatio', ...
    'LinearVelocityLateEarlyRatio','AngularVelocityLateEarlyRatio', ...
    'JointVelocityLateEarlyRatio','WorstLateEarlyOscillationRatio', ...
    'OscillationTrend'});
end

function values=windowMetrics(t,delta)
translation=delta(:,1:3);
rotationDeg=rad2deg(delta(:,4:6));
jointsDeg=rad2deg(delta(:,7:22));
translationCentered=translation-mean(translation,1);
rotationCentered=rotationDeg-mean(rotationDeg,1);
jointsCentered=jointsDeg-mean(jointsDeg,1);
linearVelocity=derivative(t,translation);
angularVelocity=derivative(t,rotationDeg);
jointVelocity=derivative(t,jointsDeg);
values=struct( ...
    "TorsoTranslationPathLength_m",sum(vecnorm(diff(translation),2,2)), ...
    "TorsoVerticalCumulativeTravel_m",sum(abs(diff(translation(:,3)))), ...
    "TorsoRotationPathLength_deg",sum(vecnorm(diff(rotationDeg),2,2)), ...
    "JointConfigurationPathLength_deg",sum(vecnorm(diff(jointsDeg),2,2)), ...
    "AbsoluteTranslationRMS_m",rms(translation,"all"), ...
    "AbsoluteRotationRMS_deg",rms(rotationDeg,"all"), ...
    "AbsoluteJointRMS_deg",rms(jointsDeg,"all"), ...
    "CenteredTranslationRMS_m",rms(translationCentered,"all"), ...
    "TranslationPeakToPeak_m",norm(max(translation,[],1)-min(translation,[],1)), ...
    "CenteredRotationRMS_deg",rms(rotationCentered,"all"), ...
    "RotationPeakToPeak_deg",norm(max(rotationDeg,[],1)-min(rotationDeg,[],1)), ...
    "CenteredJointRMS_deg",rms(jointsCentered,"all"), ...
    "MaximumJointPeakToPeak_deg",max(max(jointsDeg,[],1)-min(jointsDeg,[],1)), ...
    "TorsoLinearVelocityRMS_m_s",rms(linearVelocity,"all"), ...
    "TorsoAngularVelocityRMS_deg_s",rms(angularVelocity,"all"), ...
    "JointVelocityRMS_deg_s",rms(jointVelocity,"all"));
end

function velocity=derivative(t,values)
velocity=zeros(size(values));
for column=1:size(values,2)
    velocity(:,column)=gradient(values(:,column),t);
end
end

function ratio=safeRatio(late,early)
if early<=eps
    if late<=eps; ratio=0; else; ratio=Inf; end
else
    ratio=late/early;
end
end
