function results = consolidate_residual_rl_multiseed_evidence(outputRoot)
%CONSOLIDATE_RESIDUAL_RL_MULTISEED_EVIDENCE Summarize three SAC seeds.
%   Reads existing deterministic evaluation metrics only; it does not run
%   simulations. Boundary results retain their original evaluation horizons
%   so the 11 s and frozen 12 s evidence is not represented as identical.

arguments
    outputRoot (1,1) string = fullfile( ...
        project_codes_root(), "Results", ...
        "ResidualRLMultiSeedConsolidated", "20260817_final")
end

codesDirectory = string(project_codes_root());
if ~isfolder(outputRoot)
    mkdir(outputRoot);
end

source = struct( ...
    "seed0Formal", fullfile(codesDirectory, "Results", ...
        "ResidualRLEvaluation", "formal_20260728_162840", ...
        "evaluation_metrics.csv"), ...
    "seed0Boundary", fullfile(codesDirectory, "Results", ...
        "FrozenRL75RecoveryBoundary", "20260729_124238", ...
        "boundary_summary.csv"), ...
    "seed1Formal", fullfile(codesDirectory, "Results", ...
        "ResidualRLEvaluation", "formal_20260730_092219", ...
        "evaluation_metrics.csv"), ...
    "seed1Boundary", fullfile(codesDirectory, "Results", ...
        "FrozenSeed1RL25RecoveryBoundary", "20260730_155930", ...
        "boundary_summary.csv"), ...
    "seed2Formal", fullfile(codesDirectory, "Results", ...
        "ResidualRLEvaluationSeed2", ...
        "authority_formal_20260817_094414", ...
        "evaluation_metrics.csv"));

sourceNames = string(fieldnames(source));
sourceHashes = strings(numel(sourceNames),1);
for index = 1:numel(sourceNames)
    name = sourceNames(index);
    assert(isfile(source.(name)), ...
        "ResidualRLMultiSeed:MissingEvidence", ...
        "Required evidence is missing: %s", source.(name));
    sourceHashes(index) = fileHash(source.(name));
end
sourceManifest = table(sourceNames, ...
    string(struct2cell(source)), sourceHashes, ...
    'VariableNames', {'Source','File','SHA256'});

seed0 = readtable(source.seed0Formal, TextType="string");
seed1 = readtable(source.seed1Formal, TextType="string");
seed2 = readtable(source.seed2Formal, TextType="string");

nominal0 = selectedRow(seed0, "RL75", 0);
nominal1 = selectedRow(seed1, "RL25", 0);
nominal2 = selectedRow(seed2, "RL25", 0);

% The boundary levels below are demonstrated grid points, not interpolated
% estimates. Seed 0 and seed 1 boundary extensions used 11 s; seed 2 used
% the final frozen 12 s authority protocol.
Seed = [0;1;2];
SelectedController = ["RL75";"RL25";"RL25"];
SelectedCheckpointEpisode = [75;25;25];
FormalEvaluationHorizon_s = [11;11;12];
MaximumTestedBidirectionalRecovery_N = [185;150;150];
FirstHigherTestedNonBidirectionalLevel_N = [190;175;185];
ImprovementOverControllerA_percent = ...
    100*(MaximumTestedBidirectionalRecovery_N-100)/100;
NominalLateLateralDisplacementRMS_m = [ ...
    nominal0.LateForceInducedAxisDisplacementRMS_m; ...
    nominal1.LateForceInducedAxisDisplacementRMS_m; ...
    nominal2.LateForceInducedAxisDisplacementRMS_m];
NominalLateLateralTiltRMS_deg = [ ...
    nominal0.LateForceInducedAxisTiltRMS_deg; ...
    nominal1.LateForceInducedAxisTiltRMS_deg; ...
    nominal2.LateForceInducedAxisTiltRMS_deg];
NominalResidualTorqueRMS_Nm = [ ...
    nominal0.ResidualTorqueRMS_Nm; ...
    nominal1.ResidualTorqueRMS_Nm; ...
    nominal2.ResidualTorqueRMS_Nm];
NominalPeakResidualTorque_Nm = [ ...
    nominal0.PeakResidualTorque_Nm; ...
    nominal1.PeakResidualTorque_Nm; ...
    nominal2.PeakResidualTorque_Nm];
NominalActuatorSaturation = logical([ ...
    nominal0.ActuatorSaturation; ...
    nominal1.ActuatorSaturation; ...
    nominal2.ActuatorSaturation]);

metrics = table(Seed,SelectedController,SelectedCheckpointEpisode, ...
    FormalEvaluationHorizon_s, ...
    MaximumTestedBidirectionalRecovery_N, ...
    FirstHigherTestedNonBidirectionalLevel_N, ...
    ImprovementOverControllerA_percent, ...
    NominalLateLateralDisplacementRMS_m, ...
    NominalLateLateralTiltRMS_deg, ...
    NominalResidualTorqueRMS_Nm, ...
    NominalPeakResidualTorque_Nm,NominalActuatorSaturation);

baseline = table("Controller A",100,0, ...
    'VariableNames', {'Controller', ...
    'MaximumTestedBidirectionalRecovery_N', ...
    'ImprovementOverControllerA_percent'});

writetable(metrics,fullfile(outputRoot,"selected_seed_metrics.csv"));
writetable(baseline,fullfile(outputRoot,"controller_a_reference.csv"));
writetable(sourceManifest,fullfile(outputRoot,"source_manifest.csv"));
save(fullfile(outputRoot,"processed_results.mat"), ...
    "metrics","baseline","sourceManifest","source");

figureHandle = figure(Color="white",Position=[100 100 1050 430]);
layout = tiledlayout(1,3,TileSpacing="compact",Padding="compact");

nexttile;
bar(categorical(["A","Seed 0","Seed 1","Seed 2"]), ...
    [100;MaximumTestedBidirectionalRecovery_N],0.65, ...
    FaceColor=[0.20 0.45 0.67]);
ylabel("Maximum tested bidirectional recovery (N)");
title("Lateral recovery boundary");
ylim([0 205]); grid on;

nexttile;
bar(categorical(["Seed 0","Seed 1","Seed 2"]), ...
    NominalResidualTorqueRMS_Nm,0.65,FaceColor=[0.85 0.45 0.15]);
ylabel("Nominal residual torque RMS (N m)");
title("Nominal RL activity");
grid on;

nexttile;
bar(categorical(["Seed 0","Seed 1","Seed 2"]), ...
    NominalLateLateralTiltRMS_deg,0.65,FaceColor=[0.35 0.65 0.35]);
ylabel("Nominal late lateral tilt RMS (deg)");
title("Nominal balance deviation");
grid on;

title(layout,"Residual RL: selected-policy multi-seed evidence");
axesHandles = findall(figureHandle,Type="axes");
for index = 1:numel(axesHandles)
    axesHandles(index).Toolbar.Visible = "off";
end
exportgraphics(figureHandle, ...
    fullfile(outputRoot,"multiseed_comparison.png"),Resolution=300);
savefig(figureHandle,fullfile(outputRoot,"multiseed_comparison.fig"));

notes = [ ...
    "Three independently trained SAC seeds were evaluated deterministically."; ...
    "Controller A demonstrated bidirectional recovery at 100 N."; ...
    "Selected residual policies demonstrated 150-185 N."; ...
    "Seed 0 and seed 1 boundary extensions used 11 s; seed 2 used 12 s."; ...
    "Values are demonstrated test-grid levels, not interpolated thresholds."; ...
    "Three seeds support repeatability but do not define a precise population statistic."];
writelines(notes,fullfile(outputRoot,"interpretation_notes.txt"));

fprintf("\nSelected residual-RL policies across three seeds:\n");
disp(metrics);
fprintf("Results written to %s\n",outputRoot);

results = struct("metrics",metrics,"baseline",baseline, ...
    "sourceManifest",sourceManifest,"outputDirectory",outputRoot);
end

function row = selectedRow(metrics,controller,force_N)
selected = metrics.Controller == controller & ...
    metrics.SignedForce_N == force_N;
assert(nnz(selected)==1,"ResidualRLMultiSeed:ExpectedOneRow", ...
    "Expected one row for %s at %+.6g N; found %d.", ...
    controller,force_N,nnz(selected));
row = metrics(selected,:);
end

function hash = fileHash(path)
hash = release_file_sha256(path);
end
